=== ClearChannelOutdoor/ooh_open_direct/schema/v0/resources/products/productSearch_object.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v0/resources/products/productSearch_object.json",
    "type": "object",
    "title": "ProductSearch object",
    "description": "",
    "default": {},
    "additionalProperties": false,
    "required": [
        "AdFormatTypes",
        "Currency",
        "DeliveryType",
        "Domain",
        "Geometry",
        "TargetTypes"
    ],
    "properties": {
        "AdFormatTypes": {
            "$id": "#/properties/AdFormatTypes",
            "type": "array",
            "title": "Ad Format Types",
            "additionalItems": true,
            "items": {
                "$id": "#/properties/AdFormatTypes/items",
                "type": "string",
                "title": "The Items Schema"
            }
        },
        "Currency": {
            "$id": "#/properties/Currency",
            "type": "string",
            "title": "Currency"
        },
        "DeliveryType": {
            "$id": "#/properties/DeliveryType",
            "type": "string",
            "title": "Delivery Type"
        },
        "Domain": {
            "$id": "#/properties/Domain",
            "type": "string",
            "title": "Domain"
        },
        "Geometry": {
            "$id": "#/properties/AdvertiserId",
            "type": "array",
            "title": "Geometry",
            "description": "A list of ad format sizes that the product supports.",
            "items": {
                "$ref": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v0/common/size_object.json"
            }
        },
        "TargetTypes": {
            "$id": "#/properties/TargetTypes",
            "type": "array",
            "title": "Target Types",
            "description": "A list Target Types.",
            "items": {
                "$ref": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v0/common/targetType_object.json"
            }
        }
    }
}

=== ClearChannelOutdoor/ooh_open_direct/examples/archive/v0/products/POST_products_search_request.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v0/uris/products/products_search_request.json",
    "AdFormatTypes": [
        "HTML5",
        "Image"
    ],
    "Currency": "GBP",
    "DeliveryType": "Guaranteed",
    "Domain": "yahoo.com",
    "Geometry": [
        {
            "Width": 123,
            "Height": 456
        }
    ],
    "TargetTypes": [
        {
            "$and": [
                {
                    "Name": "Inventory",
                    "Type": "Frames",
                    "DataSource": "Space",
                    "Target": "frame_type",
                    "TargetValues": [
                        "digital moving image"
                    ]
                },
                {
                    "Name": "Inventory",
                    "Type": "Frames",
                    "DataSource": "Space",
                    "Target": "format",
                    "TargetValues": [
                        "6 sheets"
                    ]
                },
                {
                    "Name": "Inventory",
                    "Type": "Frames",
                    "DataSource": "Space",
                    "Target": "environment",
                    "TargetValues": [
                        "Rail Stations"
                    ]
                }
            ]
        }
    ]
}
