=== ClearChannelOutdoor/ooh_open_direct/schema/v1/resources/stats/stats_object.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/resources/stats/stats_object.json",
    "type": "object",
    "title": "Stats object",
    "description": "Object that describes the request for Reporting Stats",
    "default": {},
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri",
            "description": "$schema only included to aid validation of JSON, should not be used in real calls."
        },
        "AccountId": {
            "$id": "#/properties/",
            "type": "string",
            "title": "AccountId",
            "description": "The Account the Stats are for"
        },
        "OrderId": {
            "$id": "#/properties/",
            "type": "string",
            "title": "AccountId",
            "description": "The Order the Stats are for"
        },
        "LineId": {
            "$id": "#/properties/",
            "type": "string",
            "title": "AccountId",
            "description": "The Order the Stats are for"
        },
        "ReportStartDate": {
            "$id": "#/properties/",
            "type": "string",
            "format": "date",
            "title": "Start Date",
            "description": "The date report will start. if left blank, it will revert to the LineID start date"
        },
        "ReportEndDate": {
            "$id": "#/properties/",
            "type": "string",
            "format": "date",
            "title": "Start Date",
            "description": "The date report will end. if left blank, it will revert to the LineID end date"
        },
        "ReportFields": {
            "$id": "#/properties/",
            "description": "The fields that are to be included in the Stats report",
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "StartDate",
                    "EndDate",
                    "SpotLength",
                    "ShareOfTime",
                    "FrameID",
                    "CreativeID",
                    "BookedPlays",
                    "DeliveredPlays",
                    "Delivery"
                ]
            },
            "readOnly": true
        },
        "ReportGranularity": {
            "$id": "#/properties/",
            "description": "The time granularity of the Stats report",
            "type": "string",
            "enum": [
                "Flight",
                "Week",
                "Day",
                "Hour",
                "Spot"
            ],
            "maxLength": 15,
            "readOnly": true
        },
        "ReportFormat": {
            "$id": "#/properties/",
            "description": "The time granularity of the Stats report",
            "type": "string",
            "enum": [
                "Verbose",
                "NonVerbose"
            ],
            "maxLength": 15,
            "readOnly": true
        },
        "Webhook": {
            "$id": "#/properties/",
            "type": "string",
            "format": "date",
            "title": "Webhook",
            "description": "URI of the webhook to respond to"
        }
    }
}

=== ClearChannelOutdoor/ooh_open_direct/examples/OOHpenDirect_1-5-1_v-1/POST_stats_request.json
{

    "AccountId": "23873345",
    "OrderId": "3479",
    "LineId": "L1",
    "ReportStartDate": "2020-12-09 //If ReportStartDate & ReportEndDate fields are left balnk it defaults to the Campaign start and end date",
    "ReportEndDate": "2020-12-10", 
    "ReportFields":["StartDate", "EndDate","SpotLength","ShareOfTime","FrameID","CreativeID","BookedPlays", "DeliveredPlays","Delivery"],
    "ReportGranularity":"Hour",
    "ReportFormat":"Verbose",
    "Webhook": "URI which is to be notified when the stats information is available to be called from the Media Owner"

}
