=== ClearChannelOutdoor/ooh_open_direct/technical_reference/demo/local/schema/widget_object.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The Widget object",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string"
        },
        "checked": {
            "$id": "#/properties/checked",
            "type": "boolean",
            "title": "The Checked Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        },
        "dimensions": {
            "allOf": [
                {
                    "$ref": "dimensions_object.json"
                },
                {
                    "required": [
                        "width",
                        "height"
                    ]
                }
            ]
        },
        "id": {
            "$ref": "id_integer.json",
            "title": "ID ",
            "description": "ID of Widget"
        },
        "name": {
            "$ref": "name_string.json",
            "title": "Name",
            "description": "Name of the Widget"
        },
        "price": {
            "$id": "#/properties/price",
            "type": "number",
            "title": "The Price Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                12.5
            ]
        },
        "tags": {
            "$id": "#/properties/tags",
            "type": "array",
            "title": "The Tags Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    "home",
                    "green"
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/tags/items",
                "type": "string",
                "title": "The Items Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                    "home",
                    "green"
                ]
            }
        },
        "objects": {
            "$ref": "objects_array.json"
        }
    }
}

=== ClearChannelOutdoor/ooh_open_direct/technical_reference/demo/local/widget_response.json
{
    "$schema": "./schema/widget_response.json",
    "checked": false,
    "dimensions": {
        "width": 5,
        "height": 10
    },
    "id": 1,
    "name": "A green door",
    "price": 12.5,
    "tags": [
        "home",
        "green"
    ],
    "objects": [
        {
            "colour": "Red",
            "red": 255,
            "green": 0,
            "blue": 0
        },
        {
            "shape": "Square",
            "height": 100,
            "width": 100
        },
        {
            "colour": "Green",
            "red": 0,
            "green": 255,
            "blue": 0
        },
        {
            "shape": "Circle",
            "height": 10,
            "width": 10
        },
        {
            "$and": [
                {
                    "shape": "Square"
                },
                {
                    "colour": "Blue"
                }
            ]
        },
        {
            "$and": [
                {
                    "colour": "Orange"
                },
                {
                    "shape": "Triangle"
                }
            ]
        },
        {
            "$or": [
                {
                    "$and": [
                        {
                            "shape": "Square"
                        }
                    ]
                }
            ]
        },
        {
            "$and": [
                {
                    "colour": ""
                }
            ]
        }
    ]
}

=== ClearChannelOutdoor/ooh_open_direct/demo/example.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/demo/schema_example.json",
    "checked": false,
    "dimensions": {
        "width": 5,
        "height": 10
    },
    "id": 1,
    "name": "A green door",
    "price": 12.5,
    "tags": [
        "home",
        "green"
    ]
}
